# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'teste' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for teste
  pod 'MobileVLCKit', '3.3.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

target 'teste-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for teste-tvOS
  
end
